url: https://jeremy.sh

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - _config.yml
  - .gitignore
  - Gemfile
  - "*.gemspec"
  - LICENSE.txt
  - README.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed